import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js Upload File',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className="m-0 h-full p-0 antialiased"
      suppressHydrationWarning
    >
      <body className="flex h-full flex-col">
        <div className="relative text-zinc-800 dark:text-zinc-200">
          <Navbar></Navbar>

          <main className="mt-8">{children}</main>

        </div>
      </body>
    </html>
  )
}
